// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleWebData.Data;

#nullable disable

namespace SimpleWebData.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622104820_AddRefreshTokens")]
    partial class AddRefreshTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("SimpleWebData.Models.Facility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PhotoGalleryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WebSiteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PhotoGalleryId");

                    b.HasIndex("WebSiteId", "Code")
                        .IsUnique();

                    b.ToTable("Facilities");
                });

            modelBuilder.Entity("SimpleWebData.Models.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PhotoGalleryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WebSiteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PhotoGalleryId");

                    b.HasIndex("WebSiteId", "Code")
                        .IsUnique();

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("SimpleWebData.Models.PageText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WebSiteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WebSiteId");

                    b.HasIndex("PageId", "Code")
                        .IsUnique();

                    b.ToTable("PageTexts");
                });

            modelBuilder.Entity("SimpleWebData.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AltText")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("PhotoGalleryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PhotoGalleryId", "FileName")
                        .IsUnique();

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("SimpleWebData.Models.PhotoGallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WebSiteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WebSiteId", "Code")
                        .IsUnique();

                    b.ToTable("PhotoGalleries");
                });

            modelBuilder.Entity("SimpleWebData.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("FacilityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("SimpleWebData.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuperUser")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WebSiteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("WebSiteId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SimpleWebData.Models.WebSite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("WebSites");
                });

            modelBuilder.Entity("SimpleWebData.Models.Facility", b =>
                {
                    b.HasOne("SimpleWebData.Models.PhotoGallery", "PhotoGallery")
                        .WithMany()
                        .HasForeignKey("PhotoGalleryId");

                    b.HasOne("SimpleWebData.Models.WebSite", "WebSite")
                        .WithMany("Facilities")
                        .HasForeignKey("WebSiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhotoGallery");

                    b.Navigation("WebSite");
                });

            modelBuilder.Entity("SimpleWebData.Models.Page", b =>
                {
                    b.HasOne("SimpleWebData.Models.PhotoGallery", "PhotoGallery")
                        .WithMany()
                        .HasForeignKey("PhotoGalleryId");

                    b.HasOne("SimpleWebData.Models.WebSite", "WebSite")
                        .WithMany("Pages")
                        .HasForeignKey("WebSiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhotoGallery");

                    b.Navigation("WebSite");
                });

            modelBuilder.Entity("SimpleWebData.Models.PageText", b =>
                {
                    b.HasOne("SimpleWebData.Models.Page", "Page")
                        .WithMany("Texts")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpleWebData.Models.WebSite", "WebSite")
                        .WithMany("PageTexts")
                        .HasForeignKey("WebSiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Page");

                    b.Navigation("WebSite");
                });

            modelBuilder.Entity("SimpleWebData.Models.Photo", b =>
                {
                    b.HasOne("SimpleWebData.Models.PhotoGallery", "PhotoGallery")
                        .WithMany("Photos")
                        .HasForeignKey("PhotoGalleryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhotoGallery");
                });

            modelBuilder.Entity("SimpleWebData.Models.PhotoGallery", b =>
                {
                    b.HasOne("SimpleWebData.Models.WebSite", "WebSite")
                        .WithMany("PhotoGalleries")
                        .HasForeignKey("WebSiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebSite");
                });

            modelBuilder.Entity("SimpleWebData.Models.Reservation", b =>
                {
                    b.HasOne("SimpleWebData.Models.Facility", "Facility")
                        .WithMany("Reservations")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");
                });

            modelBuilder.Entity("SimpleWebData.Models.User", b =>
                {
                    b.HasOne("SimpleWebData.Models.WebSite", "WebSite")
                        .WithMany("Users")
                        .HasForeignKey("WebSiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WebSite");
                });

            modelBuilder.Entity("SimpleWebData.Models.Facility", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("SimpleWebData.Models.Page", b =>
                {
                    b.Navigation("Texts");
                });

            modelBuilder.Entity("SimpleWebData.Models.PhotoGallery", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("SimpleWebData.Models.WebSite", b =>
                {
                    b.Navigation("Facilities");

                    b.Navigation("PageTexts");

                    b.Navigation("Pages");

                    b.Navigation("PhotoGalleries");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
